### ISSUE TITLE
Generalize inception layer's pooling

### ISSUE THREAD

**Issue by bamos** [Element-Research/dpnn#11]
Hi, I'd like to use inception layers with l2 pooling, like in [FaceNet](http://arxiv.org/abs/1503.03832), but [Inception.lua](https://github.com/nicholas-leonard/dpnn/blob/bf0cf9a48edc1839fc0de835ba4a2723c4989bb0/Inception.lua#L90) only uses max pooling.

As a quick workaround for myself, I've modified the Inception layer in the master branch of my fork to accept a generic `pool` argument instead of just the size and stride of max pooling:
https://github.com/bamos/dpnn/commit/c91d263add5832d7209ab5e3d6fd20e73d6e8c97 

This works well for me, but the downside is that I've changed the API.

**Comment by bamos** [comment]
Hi, I'm about to release a project that depends on the `pool` param in my forked version. Another idea that doesn't break the API is to keep `poolSize` and `poolStride` to configure a max pooling layer as before, but also add `pool` parameter that will override the pooling layer. Thoughts?

**Comment by nicholas-leonard** [comment]
Done : 
https://github.com/nicholas-leonard/dpnn/pull/17

Keep me posted on your release!

**Comment by bamos** [comment]
Awesome, thanks @nicholas-leonard!

**Comment by bamos** [comment]
Hi @nicholas-leonard,

Thanks again for merging this PR.
I've finally released the code that depends on it at https://github.com/cmusatyalab/openface.
dpnn made writing the network much easier.

-Brandon.

**Comment by nicholas-leonard** [comment]
Awesome work brandon.

Love how detailed your README is. I added a link to your repo in the dpnn
documentaion :
https://github.com/nicholas-leonard/dpnn/blob/master/README.md#nn.Inception
.

Regards,
--Nick

Nicholas Léonard
917-741-7570
