### ISSUE TITLE
Inception: Optionally don't do 1x1 reduction or reduction after pooling.

### ISSUE THREAD

**Issue by bamos** [Element-Research/dpnn#12]
Hi, I'm interested in using inception layers, some without the 1x1 path,
and some without the reduction after pooling.
I committed my quick solution to this at https://github.com/bamos/dpnn/commit/69f7caa40378cc6b97fe4b1d6c4998ec98235a4b,
which doesn't add these layers if the `reduceSize` value is `nil`.

I'm happy to discuss alternatives and help add implementations/tests to merge this
and #11 into the master branch.

**Comment by nicholas-leonard** [comment]
Looks good. Can you submit a PR?
