### ISSUE TITLE
Cannot clone dpnn

### ISSUE THREAD

**Issue by johnny5550822** [Element-Research/dpnn#18]
I encountered this error message:

Cloning into 'dpnn'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/dpnn-scm-1.rockspec - Failed cloning git repository.

**Comment by nicholas-leonard** [comment]
Did you try : 

``` lua
luarocks install dpnn
```

Or 

``` lua
git clone git@github.com:nicholas-leonard/dpnn.git
cd dpnn
luarocks make rocks/[TAB]
```
