### ISSUE TITLE
Custom ZipTable

### ISSUE THREAD

**Issue by boknilev** [Element-Research/dpnn#25]
Hi,

I'm looking for a version of ZipTable with the following functionality:
given a table `{vec, tab}` of vector `vec` and table of vectors `tab`, produce `{ {vec, tab[1]}, {[vec tab[2}, ..., {vec tab[n]} }`, 
where `tab[i]` is the i'th element of `tab`.

Is there a way to achieve this with nn/dpnn modules? 
I wrote a module to do that based on ZipTable, but am not sure I'm getting the derivatives correctly. Here it is:

``` lua
local MyZipTable, parent = torch.class('nn.MyZipTable', 'nn.Container')

-- based on ZipTable in dpnn

-- input : { v, {a, b, c} } 
-- output : { {v,a}, {v,b}, {v,c} }
function MyZipTable:__init()
   parent.__init(self)
   self.output = {}
   self.gradInput = {}
end

function MyZipTable:updateOutput(input)
   assert(#input == 2, "input must be table of element and table")
   inputEl, inputTable = input[1], input[2]
   self.output = {}
   for i,v in ipairs(inputTable) do
      self.output[i] = {inputEl:clone(), v}
   end
   return self.output
end

function MyZipTable:updateGradInput(input, gradOutput)
   assert(#input == 2, "input must be table of element and table")
   local inputEl, inputTable = input[1], input[2]
   local gradInputEl = torch.zeros(inputEl:size())
   local gradInputTable = {}
   for i,gradV in ipairs(gradOutput) do
      gradInputEl:add(gradV[1])
      gradInputTable[i] = gradV[2]:clone()
   end
   self.gradInput = {gradInputEl, gradInputTable}
   return self.gradInput
end
```

The broader context is that I actually need to produce a table of concatenated vectors of `vec` and the elements of `tab`, i.e. `{ [vec tab[1]], [vec tab[2]], ..., [vec tab[n]] }`, but given the functionality described above I can achieve this by using nn.JoinTable inside rnn.Sequencer.
Note that I do not know the size of the table `tab` at the time the network is constructed so I cannot use nn.Replicate. 

Any help is appreciated!

P.S. if this is not the appropriate place for such an issue please advice where else I should post. Thank you.

**Comment by nicholas-leonard** [comment]
@boknilev Your code would see to be valid backprop. However, in its current form, it will be slow. So instead of a[i] = b:clone(), just do a[i] = b. You don't need to copy it. Furthermore, instead of torch.zeros() you should use a buffer that you resize and zero every forward/backward. 

I am pretty sure others could make use of that kind of module (myself included). Could make a PR to dpnn to add this module to the repository. You could call it ZipTableOneToMany. Or you could make it a special case of the ZipTable(onetomany). When onetomany = true, it calls your code.

**Comment by boknilev** [comment]
Thanks, @nicholas-leonard . How does that look? 

``` lua
local ZipTableOneToMany, parent = torch.class('nn.ZipTableOneToMany', 'nn.Container')

-- based on ZipTable in dpnn

-- input : { v, {a, b, c} } 
-- output : { {v,a}, {v,b}, {v,c} }
function ZipTableOneToMany:__init()
   parent.__init(self)
   self.output = {}
   self.gradInput = {}
   -- make buffer to update during forward/backward
   self.gradInputEl = torch.Tensor()
end

function ZipTableOneToMany:updateOutput(input)
   assert(#input == 2, "input must be table of element and table")
   local inputEl, inputTable = input[1], input[2]
   self.output = {}
   for i,v in ipairs(inputTable) do
      self.output[i] = {inputEl, v}
   end
   return self.output
end

function ZipTableOneToMany:updateGradInput(input, gradOutput)
   assert(#input == 2, "input must be table of element and table")
   local inputEl, inputTable = input[1], input[2]
   self.gradInputEl:resizeAs(inputEl):zero()
   local gradInputTable = {}
   for i,gradV in ipairs(gradOutput) do
      self.gradInputEl:add(gradV[1])
      gradInputTable[i] = gradV[2]
   end
   self.gradInput = {self.gradInputEl, gradInputTable}
   return self.gradInput
end
```

**Comment by nicholas-leonard** [comment]
@boknilev That looks great! Could you send a pull request?

**Comment by boknilev** [comment]
@nicholas-leonard See pull request at https://github.com/nicholas-leonard/dpnn/pull/26.

**Comment by nicholas-leonard** [comment]
#26
