### ISSUE TITLE
Dictionary deprecated?

### ISSUE THREAD

**Issue by elbamos** [Element-Research/dpnn#29]
I've been considering switching to Torch because I need an embedding class that only updates rows actually used in a batch.  I see there's one in this library but its been deprecated.  Why is that?  Thanks.

**Comment by nicholas-leonard** [comment]
@elbamos It should still work for 90% of cases. I deprecated it because the 10% of use cases were annoying to debug and the resulting speedup didn't seem that worth while. But you can use it if you want.
