### ISSUE TITLE
Constant.lua has a error

### ISSUE THREAD

**Issue by CosmosShadow** [Element-Research/dpnn#49]
Constant.lua has a error, at line 28.

`self.output:resize(self.size):copy(self.value)`

self.size is not initialized.

**Comment by nicholas-leonard** [comment]
@CosmosShadow https://github.com/Element-Research/dpnn/commit/9f87e08bb96dea44d43159a05a54a29dfd85d07a should fix it. Thanks for identifying this bug!

**Comment by CosmosShadow** [comment]
You are welcome.
Thank you for creating a great package for Machine Learning, and we can use it.
