### ISSUE TITLE
NaN.lua missing

### ISSUE THREAD

**Issue by ghost** [Element-Research/dpnn#50]
Hi,

I just reinstall this package and get this error message when I execute a lua script..

/home/XXX/torch/install/share/lua/5.1/trepl/init.lua:384: cannot open /home/XXX/torch/install/share/lua/5.1/dpnn/NaN.lua: No such file or directory
stack traceback:
    [C]: in function 'error'
    /home/XXX/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    XXX_cnn.lua:1: in main chunk
    [C]: in function 'dofile'
    ...XXX/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

seems NaN.lua is missing.
best regards...nice package btw

**Comment by nicholas-leonard** [comment]
@LAtanassov Sorry about that. Forgot to `git add it`. Fixed in latest commit.
