### ISSUE TITLE
The return of ReinforceNormal

### ISSUE THREAD

**Issue by GOATmessi8** [Element-Research/dpnn#53]
I wonder why the return of updataGradInput is "self.gradInput", since all your computation are "gradMean" and "gradStdev"?

**Comment by ssampang** [comment]
My reply to you in #51 should answer your question. Essentially, gradMean and gradStdev are pointing to the same storage as self.gradInput, so when you modify gradMean and gradStdev, you are modifying self.gradInput.

**Comment by GOATmessi8** [comment]
@ssampang Got it! Thanks!
