### ISSUE TITLE
nn.ArgMax CUDA compatibility

### ISSUE THREAD

**Issue by cjmcmurtrie** [Element-Research/dpnn#81]
I see that nn.ArgMax is not yet compatible with CudaTensor?

If this is so I'd be willing to help (I really need this layer on CUDA right now). Let me know what I can do - I'm not a CUDA developer but fairly experienced with Lua/Torch.

**Comment by cjmcmurtrie** [comment]
Forget that, I just needed to update dpnn.

**Comment by nicholas-leonard** [comment]
@cjmcmurtrie It is the intention that counts :P
