### ISSUE TITLE
Error while loading the package

### ISSUE THREAD

**Issue by rremani** [Element-Research/dpnn#92]
Hi guys,
I am able to install dpnn but getting an error while calling the library. Below is the message I got while installing:
root@570ccca0a1d2:/digits/dpnn# **luarocks make rocks/dpnn-scm-1.rockspec** 
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/torch/install/" -DCMAKE_INSTALL_PREFIX="/usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1" && make
   
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /usr/local/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /digits/dpnn/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialBinaryLogisticRegression.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/BinaryClassReward.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/BinaryLogisticRegression.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/OneHot.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/FireModule.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/NCECriterion.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialRegionDropout.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/CAddTensorTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Constant.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ModuleCriterion.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Convert.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/VRClassReward.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Serial.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialMaxPooling.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Collapse.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/LookupTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceBernoulli.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReverseTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Module.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceCategorical.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Inception.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Kmeans.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/init.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/BatchNormalization.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Sequential.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialConvolutionMM.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceNormal.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Clip.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/PrintSize.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ReinforceGamma.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Criterion.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialBinaryConvolution.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialBatchNormalization.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ZipTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ParallelTable.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/WhiteNoise.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialFeatNormalization.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/CategoricalEntropy.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ArgMax.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialUniformCrop.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialConvolution.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SpatialGlimpse.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/NCEModule.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/ZipTableOneToMany.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Dictionary.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Reinforce.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/Container.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/TotalDropout.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/SimpleColorTransform.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/PCAColorTransform.lua
-- Installing: /usr/local/torch/install/lib/luarocks/rocks/dpnn/scm-1/lua/dpnn/test.lua
Updating manifest for /usr/local/torch/install/lib/luarocks/rocks
dpnn scm-1 is now built and installed in /usr/local/torch/install/ (license: BSD)

Now I get the below error while I call it:
root@570ccca0a1d2:/digits/dpnn# th
 
  ______             __   |  Torch7 
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help 
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch 
                          |  http://torch.ch 
	
th> **require 'dpnn'**
/usr/local/torch/install/share/lua/5.1/trepl/init.lua:384: /usr/local/torch/install/share/lua/5.1/trepl/init.lua:384: /usr/local/torch/install/share/lua/5.1/torch/init.lua:102: bad argument #2 (invalid parent class name nn.Decorator)
stack traceback:
	[C]: in function 'error'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require 'dpnn'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0344s]	
th>

**Comment by iacolippo** [comment]
same as #91

**Comment by rremani** [comment]
Thanks @iacolippo
